routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index');

Route::get('/category', 'PagesController@allCategory');

Route::get('/category/{type}', 'PagesController@category');

Route::get('/faq', 'PagesController@faq');

Route::resource('posts', 'Post\PostController');

Route::get('/posts/{slug}','Post\PostController@show')->name('posts.show');

Route::get('/posts/{slug}/edit','Post\PostController@edit')->name('posts.edit');

Route::resource('comments', 'Post\CommentController');

Route::resource('newsletter', 'NewsletterController', ['only'=>['store','destroy']]);

Route::resource('contactus', 'ContactUsController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/inc/admin/comments.blade.php
<div class="clearfix container-fluid bg-success mt-2 mb-10">
    <span class="float-left">
        <h4>Comments</h4>
    </span>
    <span class="float-right pt-1" style="list-style: none;display:flex">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item active">Comments</li>
    </span>
</div>

 @if(count($unapprovedcomments->where("isApprove", 0)) > 0)
  <div class="row">
    @foreach ($unapprovedcomments->where("isApprove", 0) as $unapprovedcomment)
        <div class="media border p-3">
            <img src="/" alt="{{$unapprovedcomment->name}}" class="mr-3 mt-3 rounded-circle" style="width:60px;">
            <div class="media-body">
              <h4>{{$unapprovedcomment->name}} <small><i>Comment on {{$unapprovedcomment->post->title}}</i></small></h4>
              <p> - {{$unapprovedcomment->comment}}</p>
              <p>{{date('M d, Y', strtotime($unapprovedcomment->created_at))}}</p>
              <span>
                  <form role="form" method="POST" action="{{action('Post\CommentController@update', ['id' => $unapprovedcomment->id])}}">
                  {{csrf_field()}}
                  <input type="hidden" name="_method" value="PATCH">
                  <button type="submit" class="btn btn-info btn-sm">Approve</button>
                  </form>
              </span>
              <span>
                  <form role="form" method="POST" action="{{action('Post\CommentController@destroy', ['id' => $unapprovedcomment->id])}}">
              {{csrf_field()}}
              <input type="hidden" name="_method" value="DELETE">
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
              </span>
              
            </div>
      </div>
    @endforeach
  </div>
  {{$posts->links()}}
  @else 
    <div>
        <div>
            <p>No New Comment</p>
        </div>
    </div>

@endif

resources/views/inc/admin/dashboard.blade.php
@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif
@include('inc.messages')
<div class="clearfix container-fluid bg-success mt-2 mb-2">
  <span class="float-left">
     <h4>DashBoard</h4>
  </span>
</div>

<div class="card-columns card-deck">
    @if(Auth::user()->isAdmin == 1)
    <div class="card " style="background-color: #20A8D8;color:white">
        <div class="card-body text-center">
            <p class="card-text">
                <h1>{{count($posts)}}</h1>
                Posts
            </p>
        </div>
    </div> 
    <div class="card " style="background-color: #63C2DE;color:white">
        <div class="card-body text-center">
            <p class="card-text">
                <h1>{{count($unapprovedcomments)}}</h1>
                UnApprove Comments
            </p>
        </div>
    </div> 
    <div class="card " style="background-color: #FFC107;color:white">
        <div class="card-body text-center">
            <p class="card-text">
                <h1>{{count($subscribers)}}</h1>
                Subscribers
            </p>
        </div>
    </div> 
    @else 
        <div class="card col-sm-3" style="background-color: #20A8D8;color:white">
            <div class="card-body text-center">
                <p class="card-text">
                    <h1>{{count($posts->where('user_id', Auth::user()->id))}}</h1>
                    Posts
                </p>
            </div>
        </div>
    @endif
</div>
<a href="{{ route('posts.create') }}" class="btn btn-success btn-sm mb-4">Create new post</a>

      <div class="alert alert-success">
            <strong>Welcome!</strong>  <a href="#" class="alert-link"> {{ Auth::user()->name }} </a>.
          </div>
@if(Auth::user()->isAdmin !== 1)

    @include('inc.admin.posts')
@endif

resources/views/inc/admin/posts.blade.php
<div class="clearfix container-fluid bg-success mt-2 mb-10">
    <span class="float-left">
        <h4>Posts</h4>
    </span>
    <span class="float-right pt-1" style="list-style: none;display:flex">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item active">Posts</li>
    </span>
</div>
 <a href="{{ route('posts.create') }}" class="btn btn-success btn-sm">Create new post</a>
                        <br/><br/>
  @if(count($posts) > 0)

  <table class="table  table-bordered table-hover table-danger">
      <thead>
          <tr>
              <th>Title</th>
              <th>Views</th>
              <th></th>
              <th></th>
          </tr>
      </thead>

      <tbody>
        @if(Auth::user()->isAdmin == 1)
          @foreach ($posts as $post)
            <tr>
              <td> {{str_limit($post->title, 20)}}</td>
              <td> {{$post->views}}</td>
              <td>
                <a href="/posts/{{$post->slug}}/edit" class="btn btn-info btn-sm">Update</a>
              <td>
                <form role="form" method="POST" action="{{action('Post\PostController@destroy', ['id' => $post->id])}}">
                  {{csrf_field()}}
                  <input type="hidden" name="_method" value="DELETE">
                  <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
              </td>
            </tr>
          @endforeach
            {{$posts->links()}}
        @else 
            @foreach ($posts->where('user_id', Auth::user()->id) as $post)
            <tr>
              <td> {{str_limit($post->title, 20)}}</td>
              <td> {{$post->views}}</td>
              <td><button type="button" class="btn btn-info btn-sm">Update</button></td>
              <td>
                <form role="form" method="POST" action="{{action('Post\PostController@destroy', ['id' => $post->id])}}">
                  {{csrf_field()}}
                  <input type="hidden" name="_method" value="DELETE">
                  <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
              </td>
            </tr>
          @endforeach
            {{$posts->links()}}
        @endif
      </tbody>
  </table>
  @else
    <div>
      <td>No Post Found </td>
    </div>
  @endif

resources/views/inc/admin/sidemenu.blade.php
<aside class="col-sm-2" admin-menu>
    <!-- Nav tabs -->
    <ul class="nav flex-column" role="tablist">
        <li class="nav-item mt-20" id="list-group-item" >
            <a class="nav-link active" data-toggle="tab" href="#dashboard">
                <div class="clearfix">
                    <span class="float-left">Dashboard </span>
                    <span class="float-right"> > </span>
                </div>
            </a>
        </li>
        @if(Auth::user()->isAdmin === 1)
        <li class="nav-item mt-20" id="list-group-item" >
            <a class="nav-link " data-toggle="tab" href="#posts">
                <div class="clearfix">
                    <span class="float-left">Posts </span>
                    <span class="float-right"> > </span>
                </div>
            </a>
        </li>
        <li class="nav-item mt-20" id="list-group-item">
            <a class="nav-link " data-toggle="tab" href="#comments">
                <div class="clearfix">
                    <span class="float-left">Comments </span>
                    <span class="float-right"> > </span>
                </div>
            </a>
        </li>
        <li class="nav-item mt-20" id="list-group-item">
            <a class="nav-link " data-toggle="tab" href="#subscribers">
                <div class="clearfix">
                    <span class="float-left">Subscribers </span>
                    <span class="float-right"> > </span>
                </div>
            </a>
        </li>
        @endif
    </ul>
</aside>

resources/views/inc/admin/subscribers.blade.php
<div class="clearfix container-fluid bg-success mt-2 mb-2">
    <span class="float-left">
        <h4>Subscribers</h4>
    </span>
    <span class="float-right pt-1" style="list-style: none;display:flex">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item active">Subscribers</li>
    </span>
</div>

@if(count($subscribers) > 0)
    <table class="table table-hover">
        <thead>
          <tr>
            <th>Email</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($subscribers as $subscriber)
            <tr>
              <td>  {{$subscriber->email}}</td>
              <td>  {{date('M d, Y', strtotime($subscriber->created_at))}}</td>
            </tr>
          @endforeach
          {{$posts->links()}}
          </tbody>
    </table>
@else 
    <div class="pl-10">
      <p>No Subscribers so far</p>
    </div>
@endif